In [5]:
import pandas as pd
from utils import *
import itertools

READ_DATA_PATHS, WRITE_DATA_PATHS = resolve_paths(read_datasets=["Atlas Trade Data",
                                                                "Atlas Products Data",
                                                                "BACI Data",
                                                                 "UN Comtrade Reporters",
                                                                 "Graphs Data"], 
                                                write_datasets=["Graphs Data"])

### SETTINGS ###
digits = 4 # 2 or 4
################

Loading DATA_PATHS.yaml from ../../data/DATA_PATHS.yaml

## Affected Importers Label

A country is labelled as affected importer if:
 * One of its exporter partners has "lost" its condition as exporter
 * The importer either reduces its imports for the commodity by an amount of 20%; OR
 * The importer pays a higher price than the previous year, in excess of the price change for the commodity

Retrieve BACI data to compute average prices

In [6]:
avg_prices = pd.DataFrame()
avg_prices_per_importer = pd.DataFrame()
atlas_countries = load_atlas_data(READ_DATA_PATHS["Atlas Trade Data"]).country_id.unique()
all_countries = set(atlas_countries)

for year in range(2012, 2023):
    baci = pd.read_csv(READ_DATA_PATHS["BACI Data"] + f"/BACI_HS12_Y{year}_V202501.csv", dtype={"product_id": str})
    baci["product_code"] = baci.product_id.str[:digits] ## Reduce product code to {digits} digits
    baci.dropna(inplace=True) # Some entries have NANs for qty. We'll dismiss this faulty entries.
    # Calculate the average price each importer was paying for each product (across all partners)
    avg_prices_per_importer_year = baci.groupby(["importer", "product_code"])[["export_value", "qty"]].sum().reset_index()
    avg_prices_per_importer_year["price"] = avg_prices_per_importer_year.export_value / avg_prices_per_importer_year.qty
    avg_prices_per_importer_year.loc[:, ["year"]] = year
    avg_prices_per_importer = pd.concat([avg_prices_per_importer, avg_prices_per_importer_year])
    # Calculate average price per commodity-year
    avg_prices_year = baci.groupby("product_code")[["export_value", "qty"]].sum().reset_index()
    avg_prices_year["price"] = avg_prices_year.export_value / avg_prices_year.qty
    avg_prices_year["year"] = year
    avg_prices = pd.concat([avg_prices, avg_prices_year])
    # Update all seen countries
    all_countries.update(baci.exporter)
    all_countries.update(baci.importer)
    del baci # to recover some memory

Get the report of potentially affected importers by 'lost exporters'

In [8]:
# Initial report of potentially affected importers from lost exporters
drop_exporters_impact = pd.read_csv(READ_DATA_PATHS["Graphs Data"] + f"/{digits}_digits/df_impact_drop_exporters.csv")
drop_exporters_impact.rename(columns={"pid": "product_code"}, inplace=True)
drop_exporters_impact.head(3)

,affected_importer,year_from_value,year_to_value,year_from_n_exporters,year_to_n_exporters,year_from,year_to,product_code,exporter_id,drop_pct
0,250,93837296.0,99413663.0,72.0,78.0,2012,2013,0706,4,-0.653463
1,586,232856.0,63244.0,13.0,20.0,2012,2013,0706,4,-0.653463
2,124,228450441.0,171124958.0,83.0,78.0,2012,2013,1302,4,-0.544175

In [9]:
# Calculate drop in imports from potentially affected importers
drop_exporters_impact["importer_drop"] = (drop_exporters_impact["year_to_value"] / drop_exporters_impact["year_from_value"]) - 1
drop_exporters_impact.head(3)

,affected_importer,year_from_value,year_to_value,year_from_n_exporters,year_to_n_exporters,year_from,year_to,product_code,exporter_id,drop_pct,importer_drop
0,250,93837296.0,99413663.0,72.0,78.0,2012,2013,0706,4,-0.653463,0.059426
1,586,232856.0,63244.0,13.0,20.0,2012,2013,0706,4,-0.653463,-0.728399
2,124,228450441.0,171124958.0,83.0,78.0,2012,2013,1302,4,-0.544175,-0.250932

We need to find the products that 'affected importer' was importing from 'lost exporters' at 'year from', then add the avg. price of the commodity, then do the same for 'year to', and calculate the ratios.

In [10]:
# Get Avg. Price Product (APP) for year from
drop_exporters_impact = drop_exporters_impact.merge(avg_prices[["product_code", "year", "price"]], left_on=["product_code", "year_from"], \
                                                    right_on=["product_code", "year"], how="left")
drop_exporters_impact.drop("year", axis=1, inplace=True)
drop_exporters_impact.rename(columns={"price": "APP_year_from"}, inplace=True)
# Get Avg. Price Product (APP) for year to
drop_exporters_impact = drop_exporters_impact.merge(avg_prices[["product_code", "year", "price"]], left_on=["product_code", "year_to"], \
                                                    right_on=["product_code", "year"], how="left")
drop_exporters_impact.drop("year", axis=1, inplace=True)
drop_exporters_impact.rename(columns={"price": "APP_year_to"}, inplace=True)
# APP Change
drop_exporters_impact.loc[:, ["APP_Change"]] = (drop_exporters_impact.APP_year_to / drop_exporters_impact.APP_year_from) - 1

In [11]:
drop_exporters_impact.head(3)

,affected_importer,year_from_value,year_to_value,year_from_n_exporters,year_to_n_exporters,year_from,year_to,product_code,exporter_id,drop_pct,importer_drop,APP_year_from,APP_year_to,APP_Change
0,250,93837296.0,99413663.0,72.0,78.0,2012,2013,0706,4,-0.653463,0.059426,0.522776,0.573976,0.097938
1,586,232856.0,63244.0,13.0,20.0,2012,2013,0706,4,-0.653463,-0.728399,0.522776,0.573976,0.097938
2,124,228450441.0,171124958.0,83.0,78.0,2012,2013,1302,4,-0.544175,-0.250932,10.045846,8.156979,-0.188025

We need to find the products that 'affected importer' was importing from 'lost exporters' at 'year from', then add the avg. price paid by importer and avg. price of the commodity, then do the same for 'year to', and calculate the ratios.

In [12]:
# Get Avg. Price Product (APP) for year from
drop_exporters_impact = drop_exporters_impact.merge(avg_prices_per_importer[["importer", "product_code", "year", "price"]], \
                                                    left_on=["affected_importer", "product_code", "year_from"], \
                                                    right_on=["importer", "product_code", "year"], how="left")
drop_exporters_impact.drop(["importer", "year"], axis=1, inplace=True)
drop_exporters_impact.rename(columns={"price": "CPP_year_from"}, inplace=True)
# Get Avg. Price Product (APP) for year to
drop_exporters_impact = drop_exporters_impact.merge(avg_prices_per_importer[["importer", "product_code", "year", "price"]], \
                                                    left_on=["affected_importer", "product_code", "year_to"], \
                                                    right_on=["importer", "product_code", "year"], how="left")
drop_exporters_impact.drop(["importer", "year"], axis=1, inplace=True)
drop_exporters_impact.rename(columns={"price": "CPP_year_to"}, inplace=True)
# APP Change
drop_exporters_impact.loc[:, ["expected_change"]] = drop_exporters_impact.CPP_year_from * (1+drop_exporters_impact.APP_Change)

In [13]:
drop_exporters_impact["net_change"] = (drop_exporters_impact.CPP_year_to / drop_exporters_impact.expected_change) - 1

Apply conditions for affected label

In [14]:
affected_importers = drop_exporters_impact[(drop_exporters_impact.importer_drop <= -0.2) | (drop_exporters_impact.net_change >= 0.2)]

Make sure all labels are present

In [15]:
reporters = pd.read_csv(READ_DATA_PATHS["UN Comtrade Reporters"])
reporters.rename(columns={"reporterCode": "country_id"}, inplace=True)
products = pd.read_csv(READ_DATA_PATHS["Atlas Products Data"], dtype={"code": str})

all_countries.update(reporters.country_id) # Add countries from reporters (UN Comtrade)
# Generate all combinations
all_combinations = pd.DataFrame(itertools.product(all_countries, list(range(2012,2022)), \
                                                  [x for x in list(products.code.unique()) if not (x.startswith('77') or x.startswith('98') or len(x) != digits)]), columns=['country_id', 'year', 'product_code'])

In [16]:
affected_importers.head()

,affected_importer,year_from_value,year_to_value,year_from_n_exporters,year_to_n_exporters,year_from,year_to,product_code,exporter_id,drop_pct,importer_drop,APP_year_from,APP_year_to,APP_Change,CPP_year_from,CPP_year_to,expected_change,net_change
1,586,232856.0,63244.0,13.0,20.0,2012,2013,0706,4,-0.653463,-0.728399,0.522776,0.573976,0.097938,0.802125,0.588669,0.880684,-0.331578
2,124,228450441.0,171124958.0,83.0,78.0,2012,2013,1302,4,-0.544175,-0.250932,10.045846,8.156979,-0.188025,10.411271,8.605851,8.453695,0.017999
3,784,50141464.0,41740940.0,69.0,61.0,2012,2013,1302,4,-0.544175,-0.167536,10.045846,8.156979,-0.188025,4.842840,5.061004,3.932267,0.287045
5,784,2953643.0,1961648.0,48.0,48.0,2012,2013,6812,4,-0.733950,-0.335855,4.437718,4.339557,-0.022120,2.694070,5.612187,2.634479,1.130284
6,586,354024.0,60278.0,6.0,6.0,2012,2013,7001,4,-0.653528,-0.829735,0.111922,0.112610,0.006140,0.150118,0.116080,0.151040,-0.231463

In [17]:
affected_importers.info()

<class 'pandas.core.frame.DataFrame'>
Index: 84513 entries, 1 to 227248
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   affected_importer      84513 non-null  int64
 1   year_from_value        84513 non-null  float64
 2   year_to_value          84513 non-null  float64
 3   year_from_n_exporters  84513 non-null  float64
 4   year_to_n_exporters    84513 non-null  float64
 5   year_from              84513 non-null  int64
 6   year_to                84513 non-null  int64
 7   product_code           84513 non-null  object
 8   exporter_id            84513 non-null  int64
 9   drop_pct               84513 non-null  float64
 10  importer_drop          84513 non-null  float64
 11  APP_year_from          84112 non-null  float64
 12  APP_year_to            84112 non-null  float64
 13  APP_Change             84112 non-null  float64
 14  CPP_year_from          80777 non-null  float64
 15  CPP_year_to            79856 non-null  float64
 16  expected_change        80777 non-null  float64
 17  net_change             79835 non-null  float64
dtypes: float64(13), int64(4), object(1)
memory usage: 12.3+ MB

In [18]:
affected_importers.fillna(0, inplace=True)

C:\Users\ginof\AppData\Local\Temp\ipykernel_20064\3713369678.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  affected_importers.fillna(0, inplace=True)

In [19]:
affected_importers["label"] = "affected_importer"
affected_importers.rename(columns={"affected_importer": "country_id", "year_from": "year"}, inplace=True)
affected_importers = all_combinations.merge(
    affected_importers[["country_id", "year", "product_code", "label"]], on=["year", "product_code", "country_id"], how="left"
    )
affected_importers.fillna("not_affected", inplace=True)

C:\Users\ginof\AppData\Local\Temp\ipykernel_20064\1287786849.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  affected_importers["label"] = "affected_importer"
C:\Users\ginof\AppData\Local\Temp\ipykernel_20064\1287786849.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  affected_importers.rename(columns={"affected_importer": "country_id", "year_from": "year"}, inplace=True)

In [20]:
affected_importers.head(3)

   country_id  year product_code         label
0         512  2012         0101  not_affected
1         512  2012         0102  not_affected
2         512  2012         0103  not_affected

In [22]:
affected_importers.groupby(["year", "product_code", "label"]).size().reset_index()

       year product_code              label    0
0      2012         0101       not_affected  276
1      2012         0102  affected_importer    2
2      2012         0102       not_affected  274
3      2012         0103  affected_importer    6
4      2012         0103       not_affected  270
...     ...          ...                ...  ...
19807  2021         9706       not_affected  267
19808  2021         9999  affected_importer   12
19809  2021         9999       not_affected  267
19810  2021         XXXX  affected_importer    2
19811  2021         XXXX       not_affected  274

[19812 rows x 4 columns]

In [23]:
affected_importers.sort_values(
    ["year", "product_code", "country_id"]
    )[["year", "product_code", "country_id", "label"]].to_csv(WRITE_DATA_PATHS["Graphs Data"] + f"{digits}_digits/labels-affected_importers.csv", index=False)